//! Proactive AI models - Notifications, suggestions, and autonomous planning.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// A proactive notification generated by the AI assistant.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProactiveNotification {
    pub id: Uuid,
    pub workspace_id: Option<Uuid>,
    pub notification_type: NotificationType,
    pub title: String,
    pub message: String,
    pub priority: NotificationPriority,
    pub evidence: Vec<Evidence>,
    pub suggested_actions: Vec<String>,
    pub dismissible: bool,
    pub dismissed: bool,
    pub created_at: DateTime<Utc>,
    pub expires_at: Option<DateTime<Utc>>,
}

/// Type of proactive notification.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum NotificationType {
    ResumeWork,
    LongFocusSession,
    WorkspaceSwitch,
    RepeatedEdits,
    BuildFailure,
    RecurringWorkflow,
    IdlePeriod,
    ProjectCompletion,
    UnfinishedWork,
    HealthWarning,
    LearningInsight,
    RecommendationUpdate,
}

/// Priority level of a notification.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum NotificationPriority {
    Low,
    Medium,
    High,
    Critical,
}

/// Evidence supporting a notification or decision.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Evidence {
    pub source: EvidenceSource,
    pub description: String,
    pub confidence: f64,
    pub timestamp: DateTime<Utc>,
    pub metadata: serde_json::Value,
}

/// Source of evidence for AI decisions.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EvidenceSource {
    Timeline,
    ContextMemory,
    Predictive,
    Learning,
    Semantic,
    Session,
    Recommendation,
    HealthMonitor,
}

/// Resume workspace context when reopening.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResumeContext {
    pub workspace_id: Uuid,
    pub last_active: DateTime<Utc>,
    pub unfinished_work: Vec<UnfinishedWork>,
    pub open_files: Vec<String>,
    pub active_branch: Option<String>,
    pub recent_timeline: Vec<TimelineSummary>,
    pub previous_conversation_id: Option<Uuid>,
    pub context_snapshot: Option<String>,
    /// Related workspace IDs from context memory (workspace-scoped).
    pub related_workspaces: Vec<String>,
}

/// Unfinished work item detected.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UnfinishedWork {
    pub description: String,
    pub file_path: Option<String>,
    pub detected_at: DateTime<Utc>,
    pub confidence: f64,
    pub evidence: Vec<Evidence>,
}

/// Timeline event summary.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimelineSummary {
    pub event_type: String,
    pub description: String,
    pub occurred_at: DateTime<Utc>,
}

/// Autonomous execution plan requiring approval.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExecutionPlan {
    pub id: Uuid,
    pub workspace_id: Option<Uuid>,
    pub goal: String,
    pub tasks: Vec<PlanTask>,
    pub estimated_duration_minutes: i32,
    pub required_files: Vec<String>,
    pub checkpoints: Vec<String>,
    pub confidence: f64,
    pub reasoning: String,
    pub status: PlanApprovalStatus,
    pub created_at: DateTime<Utc>,
}

/// Conditional gate for a plan task. When present, the task only executes
/// once the referenced predecessor task has reached a specific outcome,
/// enabling branches that depend on earlier results.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", tag = "type", content = "task_id")]
pub enum PlanGate {
    /// Run only if the referenced task succeeded.
    AfterSuccess(Uuid),
    /// Run only if the referenced task failed (recovery/fallback path).
    AfterFailure(Uuid),
}

/// Individual task in an execution plan.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanTask {
    pub id: Uuid,
    pub description: String,
    pub dependencies: Vec<Uuid>,
    pub estimated_minutes: i32,
    pub required_files: Vec<String>,
    pub tool_name: Option<String>,
    pub arguments: Option<serde_json::Value>,
    pub completed: bool,
    /// Optional conditional gate tying this task to a predecessor outcome.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub condition: Option<PlanGate>,
}

/// Approval status for execution plans.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum PlanApprovalStatus {
    Pending,
    Approved,
    Rejected,
    Executing,
    Completed,
    Failed,
}

/// Automation permission for specific actions.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AutomationPermission {
    pub id: Uuid,
    pub workspace_id: Option<Uuid>,
    pub action_type: String,
    pub permission: PermissionLevel,
    pub granted_at: DateTime<Utc>,
    pub expires_at: Option<DateTime<Utc>>,
}

/// Permission level for automation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PermissionLevel {
    AlwaysAllow,
    AlwaysReject,
    AskEachTime,
}

/// Enhanced daily briefing with intelligence.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EnhancedBriefing {
    pub date: DateTime<Utc>,
    pub summary: String,
    pub yesterday_summary: Vec<String>,
    pub today_priorities: Vec<Priority>,
    pub unfinished_work: Vec<UnfinishedWork>,
    pub health_trends: Vec<HealthTrend>,
    pub prediction_changes: Vec<PredictionChange>,
    pub learning_insights: Vec<LearningInsight>,
    pub semantic_discoveries: Vec<SemanticDiscovery>,
    pub recommendations: Vec<String>,
    pub estimated_focus_schedule: Vec<FocusBlock>,
}

/// Priority item for today.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Priority {
    pub description: String,
    pub confidence: f64,
    pub reasoning: String,
    pub estimated_minutes: i32,
}

/// Health score trend.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HealthTrend {
    pub workspace_id: Uuid,
    pub workspace_name: String,
    pub current_score: f64,
    pub previous_score: f64,
    pub change: f64,
    pub trend: String,
}

/// Prediction confidence change.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PredictionChange {
    pub prediction_type: String,
    pub previous_confidence: f64,
    pub current_confidence: f64,
    pub change: f64,
    pub reasoning: String,
}

/// Learning insight discovered.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LearningInsight {
    pub insight_type: String,
    pub description: String,
    pub confidence: f64,
    pub discovered_at: DateTime<Utc>,
}

/// Semantic discovery from analysis.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SemanticDiscovery {
    pub discovery_type: String,
    pub description: String,
    pub files: Vec<String>,
    pub confidence: f64,
}

/// Estimated focus block.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FocusBlock {
    pub time: String,
    pub activity: String,
    pub confidence: f64,
}

/// Request to approve or reject an execution plan.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApprovalRequest {
    pub plan_id: Uuid,
    pub approved: bool,
    pub permission_level: Option<PermissionLevel>,
}

/// Timeline intelligence query result.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimelineIntelligence {
    pub query: String,
    pub answer: String,
    pub evidence: Vec<Evidence>,
    pub confidence: f64,
    pub related_events: Vec<TimelineSummary>,
}
