//! Recommendation models and types.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// A recommendation generated by the intelligence layer.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Recommendation {
    /// Unique identifier for this recommendation.
    pub id: String,

    /// Workspace this recommendation applies to.
    pub workspace_id: String,

    /// Category of recommendation.
    pub category: RecommendationCategory,

    /// Priority level.
    pub priority: RecommendationPriority,

    /// Short title/summary.
    pub title: String,

    /// Detailed description.
    pub description: String,

    /// Action the user can take.
    pub action: RecommendationAction,

    /// Confidence score (0.0 - 1.0).
    pub confidence: f64,

    /// Expected impact if acted upon (0.0 - 1.0).
    pub impact: f64,

    /// Estimated effort to implement (0.0 - 1.0, where 0 is trivial).
    pub effort: f64,

    /// When this recommendation was generated.
    pub generated_at: DateTime<Utc>,

    /// Optional expiry time (recommendation may become stale).
    pub expires_at: Option<DateTime<Utc>>,

    /// Supporting data/context for this recommendation.
    #[serde(default)]
    pub metadata: serde_json::Value,
}

/// Category of recommendation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RecommendationCategory {
    /// Workspace organization and cleanup.
    Organization,

    /// Productivity improvements.
    Productivity,

    /// Context and session management.
    Context,

    /// File management.
    Files,

    /// Search and discovery.
    Search,

    /// General workspace health.
    Health,
}

/// Priority level for recommendations.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RecommendationPriority {
    /// Low priority, nice-to-have.
    Low,

    /// Medium priority, should consider.
    Medium,

    /// High priority, important to address.
    High,

    /// Critical priority, needs immediate attention.
    Critical,
}

/// Action type for a recommendation.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum RecommendationAction {
    /// Navigate to a specific path or file.
    Navigate { path: String },

    /// Open a specific view or panel.
    OpenView { view: String },

    /// Execute a command.
    ExecuteCommand { command: String, args: Vec<String> },

    /// Informational only, no specific action.
    Info,

    /// Custom action with arbitrary data.
    Custom { data: serde_json::Value },
}

impl Recommendation {
    /// Creates a new recommendation builder.
    ///
    /// The id is derived deterministically from the stable content
    /// (workspace + category + title) rather than a random UUID, so a
    /// regenerated recommendation set keeps the same ids across calls.
    /// `explain_recommendation` relies on this: it re-runs the
    /// generators and looks the recommendation up by id.
    pub fn new(
        workspace_id: String,
        category: RecommendationCategory,
        title: impl Into<String>,
        description: impl Into<String>,
    ) -> Self {
        let title = title.into();
        let id = format!(
            "{:016x}",
            fxhash_string(&format!("{workspace_id}|{:?}|{title}", category))
        );
        Self {
            id,
            workspace_id,
            category,
            priority: RecommendationPriority::Medium,
            title: title.into(),
            description: description.into(),
            action: RecommendationAction::Info,
            confidence: 0.5,
            impact: 0.5,
            effort: 0.5,
            generated_at: Utc::now(),
            expires_at: None,
            metadata: serde_json::Value::Null,
        }
    }

    /// Sets the priority.
    pub fn with_priority(mut self, priority: RecommendationPriority) -> Self {
        self.priority = priority;
        self
    }

    /// Sets the action.
    pub fn with_action(mut self, action: RecommendationAction) -> Self {
        self.action = action;
        self
    }

    /// Sets the confidence score.
    pub fn with_confidence(mut self, confidence: f64) -> Self {
        self.confidence = confidence.clamp(0.0, 1.0);
        self
    }

    /// Sets the impact score.
    pub fn with_impact(mut self, impact: f64) -> Self {
        self.impact = impact.clamp(0.0, 1.0);
        self
    }

    /// Sets the effort score.
    pub fn with_effort(mut self, effort: f64) -> Self {
        self.effort = effort.clamp(0.0, 1.0);
        self
    }

    /// Sets the expiry time.
    pub fn with_expiry(mut self, expires_at: DateTime<Utc>) -> Self {
        self.expires_at = Some(expires_at);
        self
    }

    /// Sets metadata.
    pub fn with_metadata(mut self, metadata: serde_json::Value) -> Self {
        self.metadata = metadata;
        self
    }

    /// Checks if this recommendation has expired.
    pub fn is_expired(&self) -> bool {
        if let Some(expires_at) = self.expires_at {
            Utc::now() > expires_at
        } else {
            false
        }
    }
}

/// FNV-1a 64-bit over a string — cheap, stable, dependency-free id
/// derivation for deterministic recommendation ids.
fn fxhash_string(s: &str) -> u64 {
    let mut hash: u64 = 0xcbf29ce484222325;
    for byte in s.as_bytes() {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x100000001b3);
    }
    hash
}
